### ISSUE TITLE
figure out why client identity with PEM files doesn't work with rustls

### ISSUE THREAD

**Issue by dmitris** [camelop/rust-mtls-example#2]
It would be great to figure out the answer to the first question in https://github.com/camelop/rust-mtls-example#contributing:
> Why the code does not work with rustls-tls feature using .pem Identity?

I made a version of the example to focus on the issue (made `rustls-tls` feature the default, removed the `native-tls` section etc.):
https://github.com/dmitris/rust-mtls-example/tree/rustls-pem-debug

(also checked in the generated test certificates to make it easier to replicate the issue)

If you have any ideas on how to attack this, please share! 🙏

**Comment by ardyfeb** [comment]
just add `.use_rustls_tls()` on `Client::Builder`

**Comment by camelop** [comment]
@ardyfeb thanks for the comment and I've applied the fix in 7a8af592648df0bbe896cc1bdd299b1d6c626a3e

also ref: https://docs.rs/reqwest/0.11.14/reqwest/struct.ClientBuilder.html#method.use_rustls_tls
